# fly.toml app configuration file generated for part3-lingering-morning-8738 on 2024-12-04T09:49:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part3-lingering-morning-8738'
primary_region = 'lhr'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
